ocesql/ocesql.c
--version等のロングオプションを指定時に、Segmentation faultが発生していた問題に対応。
--incに値を指定しない場合にSegmentation faultとなる問題に対応。
=> fix(ocesql): ロングオプション指定時のSegmentation fault

dblib/ocesql.c, dblib/ocesql.h, ocesql/parser.y, ocesql/ppout.c
引数無しのCONNECT文を受け付けるように対応した。
この場合、環境変数を参照し、CONNECT処理を実行する。
=> feat(*): 引数無しのCONNECT文に対応

ocesql/errorfile.c, ocesql/ocesql.c, ocesql/ocesql.h, ocesql/ocesqlutil.c, ocesql/parser.y, ocesql/ppout.c, ocesql/scanner.l
プリコンパイル実行時の各種情報が標準出力にのみ出力されていたため、関数で共通化した。
ログファイル指定がある場合、そちらに出力する。
=> fix(ocesql): プリコンパイルのログ出力を改善

ocesql/ppout.c
INSERT文、DELETE文、UPDATE文で未定義のフィールド名をホスト変数として利用した際に、
Segmentation faultが発生する問題を修正した。
=> fix(ocesql): 未定義変数をINSERT文等で利用した際のエラーに対応

dblib/ocdb.c, dblib/ocdb.h
PostgresqlではDeclareの時点でカーソルが作成されるため、Openはダミー処理となっている。
ダミー処理の際に、誤ってRESULT_ERRORが上位関数に戻される仕様となっていたため、カーソルのCloseが正常に行われていなかった。
DUMMY処理の場合のステータスを別途作成し、この問題に対応した。
Please see the issue for details
#12
=> fix(dblib): Postgresqlで同名のカーソルを再度オープンした際エラーとなる現象を修正

ocesql/ocesql.h, ocesql/ppout.c, ocesql/scanner.l
EXEC SQL INCLUDEの後続の命令に関して、エラー、ワーニングがあった場合に出力されている行番号が異なっていた。
INCLUDEで展開さえたファイルの行数を無視するように修正。
=> fix(ocesql): INCLUDE後のエラーメッセージで行番号が異なる

Makefile.in
実行環境/本番環境での利用を想定し、ライブラリのみをインストールすることが可能なオプションを追加した
"make dblib"および"make install-dblib"にてライブラリのみを対象にビルドできる
=> feat(*): ライブラリのみのインストールオプションを追加

ocesql/ocesql.c, tests/atlocal, tests/basic, tests/basic.src/commit-rollback.at, tests/basic.src/connect-disconnect.at, tests/basic.src/declare.at, tests/basic.src/delete.at, tests/basic.src/fetch.at, tests/basic.src/insert.at, tests/basic.src/open-close.at, tests/basic.src/other-sql.at, tests/basic.src/sample.at, tests/basic.src/select.at, tests/basic.src/update.at, tests/cobol_data, tests/cobol_data.src/alphanumeric.at, tests/cobol_data.src/japanese.at, tests/cobol_data.src/numeric_signed_v.at, tests/cobol_data.src/numeric_v.at, tests/embed_db_info.sh, tests/sql_data, tests/sql_data.src/sql_type.at, tests/sqlca, tests/sqlca.at, tests/sqlca.src/connect-disconnect.at, tests/sqlca.src/insert-select-update-delete.at, tests/sqlca.src/open-fetch-close.at, tests/sqlca.src/prepare-execute.at
I solved a a compilation problem on Fedora 34 (#28).
* I added 'extern' to variables declared in both ocesql/ocesql.c and ocesql/scanner.c.
Fix test cases.
* I fix tests/atlocal to compile modules correctly.
* I removed some test cases that checks the behaviour when errors occur. The test cases are not stable.
* I fix all test cases to discard stderr since ocesql print warning messages on stderr.
=> Solve a compilation problem on Fedora 34 (#28) and fix test cases.

dblib/ocesql.c, tests/cobol_data, tests/cobol_data.at, tests/cobol_data.src/numeric_signed_trailing_v.at
I fixed create_coboldata in dblib/ocesql.c to prevent buffer overflows (#32) and added a test case checking PIC S9(n) SIGN IS TRAILING.
=> fix: fix Issue #32 and add its test case

ocesql/Makefile.am
missing part of 621b05498ea497d8fd6d4a7ebe5d1fca3880ae13 adding `EXTRA_DIST`
Sorry, I've missed that in #57
=> Makefile fix

AUTHORS, dblib/ChangeLog, dblib/ocdblog.c, dblib/ocdblog.h, dblib/ocdbutil.c, dblib/ocdbutil.h, dblib/ocesql.c
* ocdblog.h, ocdblog.c, odbcutil.c, odbcutil.h: changed magic numbers to enum ocloglevel, use a single static loglevel instead of one for each source
* ocesql.c (OCESQLEndSQL, add_prepare_list): only run debug logging code if debug logging is active
* ocesql.c (create_coboldata) [!NDEBUG]: send data to logging without unnecessary temporary string duplication
* ocdblog.h: changed definitions for LOG and ERRLOG to only call the logging functions if the current loglevel is either unknown or set to actually do that logging which saves a lot of stack changes (nice for 'step'ing with the debugger and for saving cpu cycles if logging is disabled)
* ocdbutil.c (com_get_logfile): simplified
* ocdbutil.c (env_to_loglevel): extracted from com_get_loglevel, changed default from "no log" to "log only …
=> logging improvements

dblib/ocesql.c
until now it was only set on error, so if called multiple times "until no error occurs"...
additionally return with error code on OUT_OF_MEMORY as done in other places
=> OCESQLPrepare: set SQLCA on success

.github/workflows/ubuntu-test.yml, build_aux/bootstrap
The installation process fails when executing CI.
https://github.com/yutaro-sakamoto/Open-COBOL-ESQL/runs/6017559766?check_suite_focus=true
I modified build_aux/bootstrap and solved the problem.
@GitMensch, are there any problems with this change?
=> Update: modify build_aux/bootstrap to run CI successfully.

dblib/ocdb.c, dblib/ocdbutil.c, dblib/ocesql.c, dblib/ocpgsql.c
This is a cherry-pick of 72f2f6ee0c261ffc1f8219810e35bdf47a1839f1 done by @ChihHao-Su (+conflicts solved) and was merged by @yutaro-sakamoto in September 2022 into a stale branch in #69.
As this part from the initial PR is still not integrated and missing I suggest to pull this in (and delete the stale branch "[feature/openbsd](https://github.com/opensourcecobol/Open-COBOL-ESQL/tree/feature/openbsd)" afterwards).
=> replace '#include <malloc.h>' with standard <stdlib.h>

dblib/ocesql.c
which create a wrong log message on each PREPARE and had some minor performance impact (at least with a lot of active programs that have prepared statements)
=> ocesql.c:: fix double call to add_cursor_list_with_prepare

tests/Makefile
* target `clean` only removes testsuite results
* new target `distcheck` deleting also autoconf generated scripts
* new target `check` 
* ensure helpers are available
* clean old results
* run tests
* present the logs and fail on failed tests
* clean old results
* partial support for out-of-tree builds (need to manually specify top_srcdir)
=> test improvementes (makefile)

ocesql/ocesql.h, ocesql/parser.y, ocesql/ppout.c, ocesql/scanner.l
* changed to move declaration only on new scope
* changed to c89 comment style
can be tested with
` make CC="gcc -std=c89" CPPFLAGS="-Werror=declaration-after-statement`
Note: ocesql.c done in #99
=> c89 compat for preprocessor

dblib/ocesql.c
* instead of sprintf("%d") to a local buffer - just set the digit directly
* const the bitmasks, allowing the compiler to use them directly on all optimization levls
* swap check for sign, allowing (the otherwise incorrect) 0x0F for positive values
=> COMP-3 speedup and fix non-negative

dblib/ocpgsql.c
I'm trying to use OCESQL on Windows. I wrote a simple program that does nothing but connecting to the database. While I run, I got an access violation in function `OCDB_PGSetLibErrorStatus`:
The program runs into a address very weird:
Both the "Call Stack" window and the disassembly shows the program has entered another function , but 
I checked the C code of `OCDB_PGSetLibErrorStatus`, I cannot find any function-calling at the switch statement.
I found the issue is caused by parameter name `errno`.  `errno` is a marco defined in errno.h.
So after C preprocessing, the code:
```c
int
OCDB_PGSetLibErrorStatus(struct sqlca_t *st, int errno){
switch(errno){
// ....
```
Actually becomes:
```c
int
OCDB_PGSetLibErrorStatus(struct sqlca_t *st, int *(*_errno)()){
switch(*_errno()){
// ....
``` …
=> Fix access violation on Windows

ocesql/ppout.c
Fix position of period when using "CLOSE".
```
CALL "OCESQLCursorClose"  USING
BY REFERENCE SQLCA
BY REFERENCE "close_period_C1" & x"00"
END-CALL
.
```
↓
```
CALL "OCESQLCursorClose"  USING
BY REFERENCE SQLCA
BY REFERENCE "close_period_C1" & x"00"
END-CALL.
```
=> Fix position of period when using "CLOSE"

ocesql/errorfile.c, ocesql/ocesql.c, ocesql/ocesql.h, ocesql/ppout.c
When using a variable with VARYING in a PREPARE statement, the error message "E013: variable for PREPARE should be GROUP."
Fixed so that this message does not appear.
When an error message related to an SQL statement was generated, the return code would exit with 0.
Fixed so that the return code is -1.
=> Fix error when using VARYING to PREPARE and return code on error

ocesql/scanner.l
Fixed to allow "N" and "NC" to be used in VALUE clauses.
=> Fix using N and NC in VALUE clause

ocesql/errorfile.c
When printerrormsg() was executed, the specification was that it would unconditionally set errmsgflg to 1 and cause a precompile error.
This is an error. When printerrormsg() is executed, the function basically terminates abnormally, but depending on the conditions, it may terminate normally.
Therefore, it was corrected so that a precompile error is generated only when an abnormal termination occurs.
=> Fix bug of printerrormsg
